---
- name: "enable huge pages"
  sysctl:
    name: vm.nr_hugepages
    value: "1280"
    state: present

- name: Install dependancies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - curl
    - docker.io
    - python3

- name: "template sshd config"
  template:
    src: templates/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root 
    group: root 
    mode: '0644'
  notify: restart sshd

- name: "template selfdestruct script"
  template:
    src: selfdestruct.sh.j2
    dest: /usr/local/bin/selfdestruct.sh
    owner: root
    mode: '0755'

- name: "add cronjob for selfdestruct"
  cron:
    name: "selfdestruct"
    minute: "0"
    user: root
    job: "bash /usr/local/bin/selfdestruct.sh >> /var/log/selfdestruct.log 2>&1"
    cron_file: "selfdestruct"

- name: Execute doxmr
  ignore_errors: yes
  shell: "docker rm -f xmrig; docker run -d --name xmrig --privileged --dns 1.1.1.1 --restart unless-stopped iofq/docker-xmrig:latest"
