---
- name: Install dependancies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker.io

- name: "copy sshd config"
  template:
    src: templates/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root 
    group: root 
    mode: '0644'
  notify: restart sshd

- name: "enable huge pages"
  sysctl:
    name: vm.nr_hugepages
    value: 1280
    state: present

- name: Execute doxmr
  become: true
  ignore_errors: yes
  shell: "docker rm -f xmrig; docker run --rm -d --name xmrig --privileged --dns 1.1.1.1 --restart unless-stopped iofq/docker-xmrig:latest"
