---

- name: "template sshd config"
  template:
    src: templates/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root 
    group: root 
    mode: '0644'
  notify: restart sshd

- name: "template selfdestruct script"
  template:
    src: selfdestruct.sh.j2
    dest: /usr/local/bin/selfdestruct.sh
    owner: root
    mode: '0755'

- name: "add cronjob for selfdestruct"
  cron:
    name: "selfdestruct"
    minute: "0,30"
    user: root
    job: "bash /usr/local/bin/selfdestruct.sh >> /var/log/selfdestruct.log 2>&1"
    cron_file: "selfdestruct"


