---
- hosts: localhost
  connection: local
  gather_facts: false

  # run:
  # $ export DO_API_TOKEN=your-token
  # then run this playbook to create droplet
  tasks:
    # - digital_ocean_droplet:
    #     region: sfo3 
    #     image: debian-10-x64
    #     wait: yes
    #     name: "doxmr" 
    #     size_id: s-2vcpu-4gb 
    #     state: present
    #     ssh_keys: [ '62:07:31:c0:32:b4:0c:6f:bf:ee:98:8d:d3:11:e8:c7' ] 
    #   register: new_droplet

    # - digital_ocean_tag:
    #     name: doxmr
    #     resource_id: "{{ new_droplet.data.droplet.id }}"
    #     state: present
    #   register: tag_response

    # - name: add host 
    #   add_host:
    #     name: "{{ new_droplet.data.ip_address }}"
    #     groups: "do"
    #     created: ansible_date_time

    - name: add host to hosts file
      lineinfile:
        path: "{{ inventory_file }}"
        line: "rice"

